version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: ${PROJECT_NAME}_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
  awesome-server:
    image: savarez/awesome-server:latest
    container_name: ${PROJECT_NAME}_awesome
    environment:
      AWP_DB_HOST: ${PROJECT_NAME}_db
      AWP_DB_NAME: ${POSTGRES_DB}
      AWP_DB_USER: ${POSTGRES_USER}
      AWP_DB_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
